"""etapa2_categorias_servicos_midia_reviews_favoritos

Revision ID: d1b89e58af4a
Revises: ae9b3c0b606a
Create Date: 2026-05-17 16:30:07.906435

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd1b89e58af4a'
down_revision: Union[str, None] = 'ae9b3c0b606a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('search_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('keyword', sa.String(length=255), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_logs_id'), 'search_logs', ['id'], unique=False)
    op.create_index(op.f('ix_search_logs_user_id'), 'search_logs', ['user_id'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'professional_id', name='uq_favorite_client_professional')
    )
    op.create_index(op.f('ix_favorites_client_id'), 'favorites', ['client_id'], unique=False)
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.create_index(op.f('ix_favorites_professional_id'), 'favorites', ['professional_id'], unique=False)
    op.create_table('professional_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PHOTO', 'VIDEO', name='mediatype'), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professional_media_id'), 'professional_media', ['id'], unique=False)
    op.create_index(op.f('ix_professional_media_professional_id'), 'professional_media', ['professional_id'], unique=False)
    op.create_table('professional_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professional_services_category_id'), 'professional_services', ['category_id'], unique=False)
    op.create_index(op.f('ix_professional_services_id'), 'professional_services', ['id'], unique=False)
    op.create_index(op.f('ix_professional_services_professional_id'), 'professional_services', ['professional_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_client_id'), 'reviews', ['client_id'], unique=False)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_professional_id'), 'reviews', ['professional_id'], unique=False)
    op.add_column('professionals', sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('professionals', sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('professionals', sa.Column('neighborhood', sa.String(length=255), nullable=True))
    op.add_column('professionals', sa.Column('home_service', sa.Boolean(), nullable=True))
    op.add_column('professionals', sa.Column('salon_service', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professionals', 'salon_service')
    op.drop_column('professionals', 'home_service')
    op.drop_column('professionals', 'neighborhood')
    op.drop_column('professionals', 'longitude')
    op.drop_column('professionals', 'latitude')
    op.drop_index(op.f('ix_reviews_professional_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_client_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_professional_services_professional_id'), table_name='professional_services')
    op.drop_index(op.f('ix_professional_services_id'), table_name='professional_services')
    op.drop_index(op.f('ix_professional_services_category_id'), table_name='professional_services')
    op.drop_table('professional_services')
    op.drop_index(op.f('ix_professional_media_professional_id'), table_name='professional_media')
    op.drop_index(op.f('ix_professional_media_id'), table_name='professional_media')
    op.drop_table('professional_media')
    op.drop_index(op.f('ix_favorites_professional_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_client_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_search_logs_user_id'), table_name='search_logs')
    op.drop_index(op.f('ix_search_logs_id'), table_name='search_logs')
    op.drop_table('search_logs')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
